#!/usr/bin/env python3
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.join(SCRIPT_DIR, "src")
if SRC_DIR not in sys.path:
    sys.path.insert(0, SRC_DIR)

try:
    import blizz_cli
except ModuleNotFoundError:
    print(
        "Required module 'blizz_cli' not found. Install dependencies using 'pip install -r requirements.txt' "
        "or 'pip install -e .'"
    )
    sys.exit(1)

if __name__ == "__main__":
    blizz_cli.main()
